// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXnHYcDRxHQCD1Xi_Za_jVaQFY6Ywmmvk',
    appId: '1:101151964008:web:6558040b54d342edf134dd',
    messagingSenderId: '101151964008',
    projectId: 'nutri-journey',
    authDomain: 'nutri-journey.firebaseapp.com',
    storageBucket: 'nutri-journey.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYGJPDC9O9XAPhIgp3WWstnCQmsSYWhJg',
    appId: '1:101151964008:android:b1185f47d76d6a9df134dd',
    messagingSenderId: '101151964008',
    projectId: 'nutri-journey',
    storageBucket: 'nutri-journey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvtKxH7YErVXUhxIsYk7uvtMgxhavN80s',
    appId: '1:101151964008:ios:1bae6ce4c61bd085f134dd',
    messagingSenderId: '101151964008',
    projectId: 'nutri-journey',
    storageBucket: 'nutri-journey.appspot.com',
    iosBundleId: 'com.example.nutrijourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvtKxH7YErVXUhxIsYk7uvtMgxhavN80s',
    appId: '1:101151964008:ios:1bae6ce4c61bd085f134dd',
    messagingSenderId: '101151964008',
    projectId: 'nutri-journey',
    storageBucket: 'nutri-journey.appspot.com',
    iosBundleId: 'com.example.nutrijourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXnHYcDRxHQCD1Xi_Za_jVaQFY6Ywmmvk',
    appId: '1:101151964008:web:4d789b7055a4c272f134dd',
    messagingSenderId: '101151964008',
    projectId: 'nutri-journey',
    authDomain: 'nutri-journey.firebaseapp.com',
    storageBucket: 'nutri-journey.appspot.com',
  );
}
